#!/bin/sh
# sc-help: cleans a downloads folder of NFO files, sample videos, and empty directories
# sc-category: Utilities

find . -type f -iname '*.nfo' -exec rm -i {} \;
find . -type f -iname '*sample*' -exec rm -i {} \;
find . -type d -empty -prune -exec rm -id {} \;
