#!/bin/sh
# sc-help: cleans a downloads folder of NFO files, text files, sample videos, and empty directories
# sc-category: Utilities

find . -type f -iname '*.nfo' -exec rm -i {} \;
find . -type f -iname '*.txt' -exec rm -i {} \;
find . -type f -iname '*.jpg' -exec rm -i {} \;
find . -type f -iname '*sample*' -exec rm -i {} \;
while [ -n "$(find . -type d -empty -printf '.')" ]; do
    find . -type d -empty -prune -exec rm -id {} \;
done
