#!/bin/bash
# sc-help: recursively resets directory permissions to 755 and files to 644
# sc-category: Utilities

if [ $# -eq 0 ]; then
    echo "Usage: $(basename "$0") <dirname>"
    echo "Recursively resets directory permissions to 755 and files to 644"
    exit 1
else
    if [ "$1" == "-su" ]; then
        shift
        SUDO="sudo"
    else
        SUDO=""
    fi
    $SUDO find "$1" -type f -exec chmod 644 {} \;
    $SUDO find "$1" -type d -exec chmod 755 {} \;
fi
