#!/bin/bash
# sc-help: recursively resets directory permissions to 755 and files to 644
# sc-category: Utilities

if [ $# -eq 0 ]; then
    echo "Usage: $(basename "$0") <dirname>"
    echo "Recursively resets directory permissions to 755 and files to 644"
    exit 1
else
    find "$1" -type f -exec chmod 644 {} \;
    find "$1" -type d -exec chmod 755 {} \;
fi
