#!/usr/bin/env python3
# sc-help: starts virtual machines
# sc-category: Virtual Machines
import sys
import os
import argparse
import subprocess
import shutil
import tempfile
import hashlib

# TODO: find out if I should be setting any qcow2 arguments on new images, for speed,
# or if I should use some other image type entirely

# TODO: find out if I should have a swap partition in VMs

tempdir = tempfile.TemporaryDirectory()

def parse_args():
    parser = argparse.ArgumentParser(description='Manage Virtual Machines')

    parser.add_argument('image',
        help='The disk image for the VM')
    parser.add_argument('--hostname',
        help='The hostname of the instance')
    parser.add_argument('--create-overlay-from', metavar='FILENAME',
        help='A preexisting image to use as a backing store for a new disk image')
    parser.add_argument('--copy-image-from', metavar='FILENAME',
        help='A preexisting image to copy from')
    parser.add_argument('--new-image-size', metavar='SIZE',
        help='When using --copy-image-from, specifies a size for the new image')
    parser.add_argument('--copy-into-image', action='append', nargs=2,
        metavar=('HOST_PATH','VM_PATH'),
        help='Specifies a file or directory to copy into the VM image '
            '(can be specified multiple times)')
    parser.add_argument('--user-data', action='append', metavar='FILENAME',
        help='A user data file to use (can be specified multiple times)')
    parser.add_argument('--cpus', type=int, default=2,
        help='Number of CPUs (default: %(default)s)')
    parser.add_argument('--mem', default='1G',
        help='RAM size (default: %(default)s)')
    parser.add_argument('--name',
        help='Display Name')
    # TODO: consider implementing this, maybe
    # parser.add_argument('--ephemeral', action='store_true',
    #     help='Uses a temporary copy of the image specified so that changes '
    #         'will not be saved on VM shutdown')
    parser.add_argument('--virtfs', action='append', metavar='ARGS',
        help='Adds a virtfs interface')

    # network options
    parser.add_argument('--net-nat', action='store_true',
        help='Creates a network interface that connects to a private '
            'network that uses NAT to connect to the local network')
    parser.add_argument('--net-nat-forward', action='append', nargs=3,
        metavar=('TYPE', 'HOST_ADDR', 'GUEST_PORT'),
        help="Sets the NAT network to forward a port from the host (TYPE "
            "is 'tcp' or 'udp', HOST_ADDR is either <ip>:<port> or :<port>)")
    parser.add_argument('--net-nat-restrict', action='store_true',
        help='Sets the NAT network to disallow outgoing connections completely')

    parser.add_argument('--net-bridge', action='append', nargs=3,
        metavar=('BRIDGE_NAME', 'MAC_ADDRESS', 'IP_ADDRESS'),
        help="Creates a network interface connected to a bridge (IP can "
            "specify specify subnet with '/xx' or can be set to 'dhcp')")

    return parser.parse_args()

def main():
    args = parse_args()

    # TODO: consider if you should use -nodefault
    kvm_args = ['kvm', '-nographic', '-smp', str(args.cpus), '-m', args.mem]

    # handle name
    if args.name != None:
        kvm_args += ['-name', args.name]

    # handle image
    if args.copy_image_from and args.create_overlay_from:
        sys.exit('Error: --copy-image-from and --create-overlay-from cannot '
            'be used at the same time')

    src_image = args.copy_image_from or args.create_overlay_from
    if src_image:
        if not os.path.exists(src_image):
            sys.exit('Error: {} does not exist'.format(src_image))
        if os.path.exists(args.image):
            sys.exit('Error: {} already exists'.format(args.image))
    else:
        if not os.path.exists(args.image):
            sys.exit('Error: {} does not exist'.format(args.image))

    if args.copy_image_from:
        if args.new_image_size:
            call('qemu-img', 'create', '-f', 'qcow2', args.image,
                    args.new_image_size)
            call('virt-resize', '--expand', '/dev/sda1', args.copy_image_from,
                    args.image)
        else:
            shutil.copyfile(args.copy_image_from, args.image)
    elif args.create_overlay_from:
        call('qemu-img', 'create', '-f', 'qcow2',
                '-b', args.create_overlay_from, args.image)

    if args.copy_into_image:
        for host_path, vm_path in args.copy_into_image:
            call('virt-copy-in', '-a', args.image, host_path, vm_path)

    kvm_args += ['-drive',
            'file={},if=virtio'.format(args.image.replace(',',',,'))]

    # add config disk
    instance_id = 'iid-' + hashlib.sha256(args.image.encode('utf-8')).hexdigest()
    config_disk_img = create_config_disk(
            instance_id = instance_id,
            hostname    = args.hostname,
            user_data   = args.user_data)
    kvm_args += ['-drive',
            'file={},if=virtio'.format(config_disk_img.replace(',',',,'))]

    # handle networking
    net_count = 0
    if args.net_nat:
        nat_args = ['id=net{}'.format(net_count)]
        nat_args += ['restrict={}'.format('on' if args.net_nat_restrict else 'off')]
        if args.net_nat_forward:
            for type, host_addr, guest_port in args.net_nat_forward:
                if type not in ('tcp', 'udp'):
                    sys.exit('Error: NAT forward type must be tcp or udp')
                nat_args += ['hostfwd={}:{}-:{}'.format(type, host_addr, guest_port)]

        kvm_args += ['-device', 'virtio-net,netdev=net{}'.format(net_count)]
        kvm_args += ['-netdev', 'user,{}'.format(','.join(nat_args))]
        net_count += 1

    if args.net_bridge:
        helper = get_helper()
        for bridge_name, mac_addr, ip_addr in args.net_bridge:
            kvm_args += ['-device', 'virtio-net,netdev=net{},mac={}'
                    .format(net_count, mac_addr)]
            kvm_args += ['-netdev', 'bridge,id=net{},br={},helper={}'
                    .format(net_count, bridge_name, helper)]
            # TODO: set IP address as well
        net_count += 1

    # handle virtfs
    if args.virtfs:
        for fs_args in args.virtfs:
            kvm_args += ['-virtfs', fs_args]

    call(*kvm_args)

def call(*args):
    print('$ ' + ' '.join(args))
    subprocess.check_call(args)

def create_config_disk(instance_id, hostname = None, user_data = None, dsmode = None):
    # https://cloudinit.readthedocs.org/en/latest/topics/datasources.html#no-cloud
    user_data = user_data or ['/dev/null']
    dsmode    = dsmode    or 'net'
    temp_user_data   = os.path.join(tempdir.name, 'user-data')
    temp_meta_data   = os.path.join(tempdir.name, 'meta-data')
    temp_config_disk = os.path.join(tempdir.name, 'config-disk.img')

    if len(user_data) == 1:
        shutil.copyfile(user_data[0], temp_user_data)
    else:
        call('write-mime-multipart', '-o', temp_user_data, *user_data)

    with open(temp_meta_data, 'w') as f:
        f.write('instance-id: {}\n'.format(instance_id))
        if hostname != None:
            f.write('local-hostname: {}\n'.format(hostname))
        f.write('dsmode: {}\n'.format(dsmode))
        f.flush()

    call('genisoimage', '-output', temp_config_disk, '-volid', 'cidata',
            '-joliet', '-rock', temp_user_data, temp_meta_data)

    return temp_config_disk

def get_helper():
    # TODO: find a better way to do this
    from stat import S_ISUID
    path = '/usr/lib/qemu/qemu-bridge-helper'
    if not (os.stat(path).st_mode & S_ISUID):
        sys.exit(('Error: {0} has incorrect permissions, '
            'maybe you need to run this?\n'
            'sudo dpkg-statoverride --update --add root shane 4754 {0}')
                .format(path))
    return path

if __name__ == '__main__':
    main()
